version: '3'

services:
  mysql_master_1:
    image: mysql:latest
    container_name: mysql_master_1
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica
    networks:
      - mysql_network

  mysql_master_2:
    image: mysql:latest
    container_name: mysql_master_2
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
      MYSQL_LOG_BIN: mysql-bin
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica
    networks:
      - mysql_network

  phpmyadmin_1:
    image: phpmyadmin:latest
    container_name: phpmyadmin_1
    ports: 
      - 8080:80
    environment:
      - PMA_HOST=mysql_master1
      - PMA_USER=root
      - PMA_PASSWORD=root
      
    depends_on:
      - mysql_master_1
    networks:
      - mysql_network

  phpmyadmin_2:
    image: phpmyadmin:latest
    container_name: phpmyadmin_2
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql_master2
      - PMA_USER=root
      - PMA_PASSWORD=root
     
    depends_on:
      - mysql_master_2
    networks:
      - mysql_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - phpmyadmin_1
      - phpmyadmin_2
    networks:
      - mysql_network

networks:
  mysql_network: