version: '3'

services:
  mysql_master1:
    image: mysql:latest
    container_name: mysql_master1
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=replica
      
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica

  mysql_master2:
    image: mysql:latest
    container_name: mysql_master2
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=replica
      
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica

  phpmyadmin1:
    image: phpmyadmin:latest
    container_name: phpmyadmin1
    ports:
      - "8181:80"
    environment:
      - PMA_HOST=mysql_master1
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mysql_master1

  phpmyadmin2:
    image: phpmyadmin:latest
    container_name: phpmyadmin2
    ports:
      - "8282:80"
    environment:
      - PMA_HOST=mysql_master2
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mysql_master2

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - phpmyadmin1
      - phpmyadmin2
